<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>BuyArticlesSuite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>b0c01db5-cbb8-4274-9bba-f0208df5ce50</testSuiteGuid>
   <testCaseLink>
      <guid>490c7a67-cfe8-4ffe-ade9-aa92f5c1e078</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <iterationNameVariable>
         <defaultValue>''</defaultValue>
         <description></description>
         <id>1ed308cd-5991-479b-9e6c-1a98793aee99</id>
         <masked>false</masked>
         <name>article</name>
      </iterationNameVariable>
      <testCaseId>Test Cases/completeCheckout</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DATA_COLUMN</type>
         <value></value>
         <variableId>1ed308cd-5991-479b-9e6c-1a98793aee99</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
