<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Your Store</name>
   <tag></tag>
   <elementGuidId>d1e9b0de-845a-40b4-9a6e-6c736453d313</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h1 > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='logo']/h1/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>391b619d-a347-4084-855a-3aae086832b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://opencart.abstracta.us:80/index.php?route=common/home</value>
      <webElementGuid>d8e5d8f2-aea3-48fe-9a44-f2d957f7527f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Your Store</value>
      <webElementGuid>39fddb23-6c92-4b4d-a4b5-158b19f594ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;logo&quot;)/h1[1]/a[1]</value>
      <webElementGuid>648f4617-60cf-4b1a-9a4f-1791e0355302</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='logo']/h1/a</value>
      <webElementGuid>01e39a98-1507-4793-a230-3eee41650b07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Your Store')]</value>
      <webElementGuid>008da972-830a-44a0-b497-e69c81f38b4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Checkout'])[1]/following::a[1]</value>
      <webElementGuid>221f2294-972d-4df4-bd80-b7880b56ea14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shopping Cart'])[1]/following::a[2]</value>
      <webElementGuid>dac08995-66aa-4327-9310-1571a344cfce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Categories'])[1]/preceding::a[1]</value>
      <webElementGuid>8efeb626-cae0-4fd3-bd87-28951f1c1889</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Desktops'])[1]/preceding::a[1]</value>
      <webElementGuid>3e11f87c-6489-49bc-aeb1-35e4034ecfcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://opencart.abstracta.us:80/index.php?route=common/home']</value>
      <webElementGuid>da8517b6-b8e9-43a6-a9c7-ed782bb99f8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1/a</value>
      <webElementGuid>fb7e5f5a-59a2-42f1-870a-a59498fcbe04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://opencart.abstracta.us:80/index.php?route=common/home' and (text() = 'Your Store' or . = 'Your Store')]</value>
      <webElementGuid>3bbb68dd-63d0-4977-9673-72b9dfbd2dea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
