<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_fa fa-shopping-cart</name>
   <tag></tag>
   <elementGuidId>e8b73032-d6e7-44e8-a2e4-d08063071f1e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/div[2]/div/div/div[3]/button/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.button-group > button[type=&quot;button&quot;] > i.fa.fa-shopping-cart</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>826d4c77-dd9b-49a9-a181-e3ae3ef7b312</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-shopping-cart</value>
      <webElementGuid>cfadb3f3-ba89-4e7e-b905-a03777a792bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;product-layout col-lg-3 col-md-3 col-sm-6 col-xs-12&quot;]/div[@class=&quot;product-thumb transition&quot;]/div[@class=&quot;button-group&quot;]/button[1]/i[@class=&quot;fa fa-shopping-cart&quot;]</value>
      <webElementGuid>093ff580-d042-49ea-ad56-81cb5ff6c90d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div[2]/div/div/div[3]/button/i</value>
      <webElementGuid>405b37f6-4b27-478f-8609-cebcaf4a038a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button/i</value>
      <webElementGuid>82b47d34-73ec-4ad0-8cb1-bddf7c272b89</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
