<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputbutton-shipping-method</name>
   <tag></tag>
   <elementGuidId>f0ed1100-ad5c-455f-92ad-f602d6f9f8f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#button-shipping-method</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='button-shipping-method']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>41d2dd50-ffac-4439-a45c-921eb336a8a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2484303d-88a0-4766-9742-6687ecb59066</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Continue</value>
      <webElementGuid>e2dbc5ed-6bd8-48df-b3f6-56f299c99366</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>button-shipping-method</value>
      <webElementGuid>228b60f5-2d2a-4ca7-ab4b-6de031abfccc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-loading-text</name>
      <type>Main</type>
      <value>Loading...</value>
      <webElementGuid>ad957acb-1bb2-46d6-a276-d60172fb7fef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>236bf12b-55de-49c2-a2c4-7735755a31e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;button-shipping-method&quot;)</value>
      <webElementGuid>c78e0445-1e0c-40e5-b4f6-7976ee1af704</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='button-shipping-method']</value>
      <webElementGuid>d3787e52-6c85-4776-8cda-40dbde6aad57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='collapse-shipping-method']/div/div[2]/div/input</value>
      <webElementGuid>319324df-8b6e-450f-b94a-03507ee9974f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/input</value>
      <webElementGuid>f62c0ba3-a773-4dee-a6f8-2f09db844833</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'button-shipping-method']</value>
      <webElementGuid>6b152180-4c4b-43bf-b536-4998fa318ef2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
