<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputbutton-payment-method</name>
   <tag></tag>
   <elementGuidId>83e5b4c4-c37e-4d0a-ae16-5fd66bf2898d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#button-payment-method</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='button-payment-method']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ad10fa0b-3e79-4449-9f2c-c3efbb41c666</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>29a0b04a-cf2b-4579-a92b-ec5b0720fd4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Continue</value>
      <webElementGuid>1f87fefc-f4e2-4d1e-9493-8ba9b85e534a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>button-payment-method</value>
      <webElementGuid>77a45b07-b664-4ea1-9566-329c617f21c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-loading-text</name>
      <type>Main</type>
      <value>Loading...</value>
      <webElementGuid>eb01c820-d644-42d3-90e3-dc4fa5aa2c36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>c1440ff5-ab0e-4113-82af-ddabb81ff29c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;button-payment-method&quot;)</value>
      <webElementGuid>6106c4be-7268-4204-8017-1ec7580cf1ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='button-payment-method']</value>
      <webElementGuid>d02eed69-d265-4c72-bcfa-2fb663426c8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='collapse-payment-method']/div/div[3]/div/input[2]</value>
      <webElementGuid>f726934d-68a5-4810-9b1a-3ab606057360</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input[2]</value>
      <webElementGuid>a3e5d502-76a4-4e5a-8c00-2f594e9a9607</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'button-payment-method']</value>
      <webElementGuid>51096c8e-6b25-4610-97fa-f3c59e7046bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
