<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputbutton-confirm</name>
   <tag></tag>
   <elementGuidId>e5fddbdc-eb08-4776-a735-6942ab085e13</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#button-confirm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='button-confirm']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4ac23725-ed5c-4615-8d57-92085a3b45a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0f45d443-3808-4706-9039-4ad391b7a9b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Confirm Order</value>
      <webElementGuid>cae94969-9164-4fa5-949d-0221980dc6d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>button-confirm</value>
      <webElementGuid>fd3678b2-977c-49e8-b91d-924f46946289</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-loading-text</name>
      <type>Main</type>
      <value>Loading...</value>
      <webElementGuid>0ead03a7-f584-47d1-9c0c-9735bb35e3f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>96653f64-9886-4702-9349-0ce388f7052a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;button-confirm&quot;)</value>
      <webElementGuid>8122308f-c9c4-4426-a368-6dfcc0b50e7c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='button-confirm']</value>
      <webElementGuid>eb80d968-507c-4bac-82a7-5bbc4be20f6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='collapse-checkout-confirm']/div/div[2]/div/input</value>
      <webElementGuid>c9e1c6cd-6583-45ce-b7e7-742a5c4d4d7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/div/div[2]/div/input</value>
      <webElementGuid>c38836ae-3fe2-454a-9ed5-ffc34d8e0c07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'button-confirm']</value>
      <webElementGuid>ac5e777c-cf1b-4530-82ff-4df15a02cf20</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
