<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Your order has been placed</name>
   <tag></tag>
   <elementGuidId>e5b3c353-8d04-4ee5-8911-32714ad1412e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#content > h1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>787083bb-3bd7-46fe-941f-248ea5e9c400</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Your order has been placed!</value>
      <webElementGuid>8a8eb6fd-e004-4f6c-8eec-220bfae70858</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/h1[1]</value>
      <webElementGuid>ded53020-f372-4998-b4a5-db860cb617b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/h1</value>
      <webElementGuid>df73f9b9-4cea-468c-bc69-4b0b7f17ce73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/h1</value>
      <webElementGuid>71102b27-7282-40bf-b0cb-eafb26d9b164</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Your order has been placed!' or . = 'Your order has been placed!')]</value>
      <webElementGuid>33fb70ca-0347-4f30-a757-e8d635d2c89e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
