<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Thanks for shopping with us online</name>
   <tag></tag>
   <elementGuidId>bce6a0a7-d0f9-46e9-80c2-577551f19396</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p:nth-of-type(5)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/p[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>45c4d4e3-e8de-4981-8076-9f89f6cf94da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Thanks for shopping with us online!</value>
      <webElementGuid>95dfc5a9-7238-4155-ab1f-719bd6a616e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/p[5]</value>
      <webElementGuid>777312f2-b09f-404a-97a2-6e1a5456c5d5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/p[5]</value>
      <webElementGuid>d80828cf-02f7-45fc-8b06-070dcab21d53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[5]</value>
      <webElementGuid>171e84e0-fa66-4975-9c83-9bdfa861affc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Thanks for shopping with us online!' or . = 'Thanks for shopping with us online!')]</value>
      <webElementGuid>0d2c439e-5e02-49e0-b459-8ac4ad3f3ea5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
